# Generated by Django 2.1.2 on 2018-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(default='default_blog_image.png', upload_to='blog_pictures'),
        ),
    ]
